CREATE TABLE IF NOT EXISTS People(
    PersonID INTEGER PRIMARY KEY AUTOINCREMENT,
    FullName TEXT NOT NULL,
    DateOfBirth TEXT NOT NULL,
    ScreenName TEXT NOT NULL,
    IsAdult INTEGER NOT NULL CHECK(IsAdult IN (0,1))
)